### ISSUE TITLE
When I npm install in my test of anvil-connect in my windows7 box, it fails as below

### ISSUE THREAD

**Issue by henryleu** [anvilresearch/connect#46] opened 2014-07-16 09:06 UTC
D:\dev\codebase\cn\xdf\centrum>npm install
npm http GET https://registry.npmjs.org/anvil-connect
npm http 304 https://registry.npmjs.org/anvil-connect
npm http GET https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/base64url
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/connect-redis
npm http GET https://registry.npmjs.org/bucker
npm http GET https://registry.npmjs.org/cookie-parser
npm http GET https://registry.npmjs.org/cors
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/iniparser
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/jwa
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/mellt
npm http GET https://registry.npmjs.org/modinha
npm http GET https://registry.npmjs.org/modinha-redis
npm http GET https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/passport-facebook
npm http GET https://registry.npmjs.org/passport-google
npm http GET https://registry.npmjs.org/passport-google-oauth
npm http GET https://registry.npmjs.org/passport-http-bearer
npm http GET https://registry.npmjs.org/passport-local
npm http GET https://registry.npmjs.org/passport-twitter
npm http GET https://registry.npmjs.org/uri-js
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/express-session
npm http GET https://registry.npmjs.org/form-urlencoded
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/body-parser
npm http 304 https://registry.npmjs.org/base64url
npm http 304 https://registry.npmjs.org/connect-redis
npm http 304 https://registry.npmjs.org/cookie-parser
npm http 304 https://registry.npmjs.org/bucker
npm http 304 https://registry.npmjs.org/cors
npm http 304 https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/iniparser
npm http 304 https://registry.npmjs.org/jade
npm http 304 https://registry.npmjs.org/jwa
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/mellt
npm http 304 https://registry.npmjs.org/modinha
npm http 304 https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/modinha-redis
npm http 304 https://registry.npmjs.org/passport
npm http 304 https://registry.npmjs.org/passport-facebook
npm http 304 https://registry.npmjs.org/passport-google-oauth
npm http 304 https://registry.npmjs.org/passport-google
npm http 304 https://registry.npmjs.org/passport-http-bearer
npm http 304 https://registry.npmjs.org/express-session
npm http 304 https://registry.npmjs.org/passport-local
npm http 304 https://registry.npmjs.org/passport-twitter
npm http 304 https://registry.npmjs.org/redis
npm http 304 https://registry.npmjs.org/uri-js
npm http 304 https://registry.npmjs.org/form-urlencoded
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/yargs
npm http GET https://registry.npmjs.org/cookie
npm http GET https://registry.npmjs.org/cookie-signature
npm http GET https://registry.npmjs.org/passport-strategy
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/passport-openid
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/raw-body
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/passport-oauth
npm http GET https://registry.npmjs.org/passport-oauth1
npm http GET https://registry.npmjs.org/xtraverse
npm http GET https://registry.npmjs.org/passport-oauth2
npm http GET https://registry.npmjs.org/uid2
npm http GET https://registry.npmjs.org/utils-merge
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/cookie
npm http GET https://registry.npmjs.org/buffer-crc32
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/cookie-signature
npm http 304 https://registry.npmjs.org/cookie
npm http GET https://registry.npmjs.org/revalidator
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/passport-openid
npm http 304 https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/jsonfile
npm http GET https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/passport-oauth
npm http GET https://registry.npmjs.org/pause
npm http 304 https://registry.npmjs.org/passport-strategy
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/nodemailer
npm http 304 https://registry.npmjs.org/uid2
npm http 304 https://registry.npmjs.org/raw-body
npm http 304 https://registry.npmjs.org/passport-oauth2
npm http 304 https://registry.npmjs.org/xtraverse
npm http 304 https://registry.npmjs.org/utils-merge
npm http 304 https://registry.npmjs.org/cookie
npm http 304 https://registry.npmjs.org/buffer-crc32
npm http 304 https://registry.npmjs.org/passport-oauth1
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/revalidator
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/ncp
npm http 304 https://registry.npmjs.org/jsonfile
npm http 304 https://registry.npmjs.org/pause
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/nodemailer
npm http GET https://registry.npmjs.org/mute-stream
npm http GET https://registry.npmjs.org/readline2
npm http GET https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/bytes
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/cli-color
npm http 304 https://registry.npmjs.org/mute-stream
npm http GET https://registry.npmjs.org/openid
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/readline2
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bytes
npm http GET https://registry.npmjs.org/merge-descriptors
npm http GET https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/path-to-regexp
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/fresh
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/send
npm http 304 https://registry.npmjs.org/openid
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/serve-static
npm http 304 https://registry.npmjs.org/path-to-regexp
npm http GET https://registry.npmjs.org/oauth
npm http 304 https://registry.npmjs.org/accepts
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/fresh
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/merge-descriptors
npm http 304 https://registry.npmjs.org/send
npm http 304 https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/xmldom
npm http 304 https://registry.npmjs.org/oauth
npm http GET https://registry.npmjs.org/ms
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/xmldom

> bcrypt@0.7.8 install D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bcrypt
> node-gyp rebuild

D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bcrypt>node "D:\dev\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find WindowsSDKDir variable
 from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [D:\dev\codebase\cn\xdf\centrum\nod
e_modules\anvil-connect\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.targets(146,5): error MSB6006: "CL.exe" exited with code
-1073741515. [D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\dev\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\dev\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bcrypt
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/ms
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/negotiator
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/negotiator
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/d
npm http GET https://registry.npmjs.org/memoizee
npm http GET https://registry.npmjs.org/timers-ext
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/directmail
npm http GET https://registry.npmjs.org/simplesmtp
npm http GET https://registry.npmjs.org/mailcomposer
npm http GET https://registry.npmjs.org/he
npm http GET https://registry.npmjs.org/public-address
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/d
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/simplesmtp
npm http 304 https://registry.npmjs.org/mailcomposer
npm http GET https://registry.npmjs.org/transformers
npm http GET https://registry.npmjs.org/character-parser
npm http GET https://registry.npmjs.org/with
npm http GET https://registry.npmjs.org/monocle
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/directmail
npm http GET https://registry.npmjs.org/constantinople
npm http 304 https://registry.npmjs.org/he
npm http 304 https://registry.npmjs.org/transformers
npm http 304 https://registry.npmjs.org/character-parser
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/with
npm http 304 https://registry.npmjs.org/public-address
npm http 304 https://registry.npmjs.org/monocle
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/constantinople
npm http 304 https://registry.npmjs.org/timers-ext
npm http GET https://registry.npmjs.org/readdirp
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/css
npm http GET https://registry.npmjs.org/mimelib
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/follow-redirects
npm http GET https://registry.npmjs.org/dkim-signer
npm http GET https://registry.npmjs.org/isarray
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/next-tick
npm http GET https://registry.npmjs.org/rai
npm http GET https://registry.npmjs.org/xoauth2
npm http 304 https://registry.npmjs.org/readdirp
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/css
npm http 304 https://registry.npmjs.org/mimelib
npm http 304 https://registry.npmjs.org/isarray
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/follow-redirects
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/dkim-signer
npm http GET https://registry.npmjs.org/is-promise
npm http 304 https://registry.npmjs.org/xoauth2
npm http GET https://registry.npmjs.org/css-parse
npm http GET https://registry.npmjs.org/css-stringify
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/lru-queue
npm http GET https://registry.npmjs.org/encoding
npm http GET https://registry.npmjs.org/addressparser
npm http 304 https://registry.npmjs.org/is-promise
npm http 304 https://registry.npmjs.org/css-parse
npm http 304 https://registry.npmjs.org/css-stringify
npm http 304 https://registry.npmjs.org/rai
npm http 304 https://registry.npmjs.org/lru-queue
npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/addressparser
npm http 304 https://registry.npmjs.org/encoding
npm http 304 https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm ERR! Error: ENOENT, chmod 'D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\inquirer\node_modules\cli-color\node_m
odules\es5-ext\object\assign\shim.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\dev\\nodejs\\\\node.exe" "D:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\dev\codebase\cn\xdf\centrum
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.9
npm ERR! path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\inquirer\node_modules\cli-color\node_modules\es5-ext\ob
ject\assign\shim.js
npm ERR! fstream_path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\inquirer\node_modules\cli-color\node_modules\es
5-ext\object\assign\shim.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack D:\dev\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\with\node_modules\ug
lify-js\test\compress\concat-strings.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\dev\\nodejs\\\\node.exe" "D:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\dev\codebase\cn\xdf\centrum
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.9
npm ERR! path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\with\node_modules\uglify-js\test\comp
ress\concat-strings.js
npm ERR! fstream_path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\with\node_modules\uglify-js\t
est\compress\concat-strings.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack D:\dev\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! EEXIST, mkdir 'D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bucker\node_modules\moment\test\moment'
File exists: D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bucker\node_modules\moment\test\moment
Move it away, and try again.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\dev\\nodejs\\\\node.exe" "D:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\dev\codebase\cn\xdf\centrum
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.9
npm ERR! path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bucker\node_modules\moment\test\moment
npm ERR! fstream_path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\bucker\node_modules\moment\test\moment\getters_
setters.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack D:\dev\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
npm ERR! fstream_stack D:\dev\nodejs\node_modules\npm\node_modules\mkdirp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\monocle\node_modules
\readdirp\examples\node_modules\tap-stream\node_modules\through\LICENSE.APACHE2'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\dev\\nodejs\\\\node.exe" "D:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\dev\codebase\cn\xdf\centrum
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.9
npm ERR! path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\monocle\node_modules\readdirp\example
s\node_modules\tap-stream\node_modules\through\LICENSE.APACHE2
npm ERR! fstream_path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\monocle\node_modules\readdirp
\examples\node_modules\tap-stream\node_modules\through\LICENSE.APACHE2
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack D:\dev\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/wordwrap
npm ERR! Error: ENOENT, lstat 'D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\transformers\node_mo
dules\uglify-js\node_modules\source-map\build\test-suffix.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\dev\\nodejs\\\\node.exe" "D:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\dev\codebase\cn\xdf\centrum
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.9
npm ERR! path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\transformers\node_modules\uglify-js\n
ode_modules\source-map\build\test-suffix.js
npm ERR! fstream_path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\transformers\node_modules\ugl
ify-js\node_modules\source-map\build\test-suffix.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack D:\dev\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\transformers\node_mo
dules\uglify-js\node_modules\optimist\node_modules\wordwrap\test\idleness.txt'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\dev\\nodejs\\\\node.exe" "D:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\dev\codebase\cn\xdf\centrum
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.9
npm ERR! path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\transformers\node_modules\uglify-js\n
ode_modules\optimist\node_modules\wordwrap\test\idleness.txt
npm ERR! fstream_path D:\dev\codebase\cn\xdf\centrum\node_modules\anvil-connect\node_modules\jade\node_modules\transformers\node_modules\ugl
ify-js\node_modules\optimist\node_modules\wordwrap\test\idleness.txt
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack D:\dev\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/amdefine
npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.8 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\dev\\nodejs\\\\node.exe" "D:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\dev\codebase\cn\xdf\centrum
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/amdefine

**Comment by christiansmith** [comment] 2015-06-27 18:59
@bnb is now helping with Windows support.

**Comment by bnb** [comment] 2015-06-29 22:30
Python 2.7 and another tool (which I can't find or remember now, since it was trivial to solve it) are also required. See https://github.com/anvilresearch/connect/issues/100 for a discussion of the solution.

**Comment by vsimonian** [comment] 2015-07-22 02:21
Is this issue essentially a duplicate of #100?

**Comment by christiansmith** [comment] 2015-08-05 19:02
@vsimonian it appears so.

**Closed** 2015-08-14 03:44 UTC
Labels: duplicate
