### ISSUE TITLE
Stored consent given by users to non-trusted client applications

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/connect#281] opened 2015-10-21 21:22 UTC
As far as I know this isn't mentioned anywhere in the spec but it seems to be a common feature in current implementations of OIDC such as Google, GitHub and Facebook.

**Comment by EternalDeiwos** [comment] 2015-10-21 21:22
Current behavior is to ask for after each login.

**Comment by christiansmith** [comment] 2015-11-27 20:07
This looks like a duplicate of #26. We can probably sort it out in one or two pairing sessions.

**Comment by christiansmith** [comment] 2015-11-28 23:45
Great work on #299 @EternalDeiwos. Thanks!

**Closed by christiansmith** 2015-11-28 23:45 UTC
Labels: duplicate, enhancement, question
